algoritmo "AreaTrapezio"
var
   //Declaracao de variaveis
   Bmaior,bmenor,altura,area:real
inicio
   //Entrada de Dados
   escreva("Digite o valor da Base maior: " )
   leia(Bmaior)
   
   escreva("Digite o valor da base menor: " )
   leia(bmenor)
   
   escreva("Digite o valor da altura: " )
   leia(altura)
   
   
   //Processamento
   area<- (Bmaior+bmenor) * altura/2
   
   
   //Saida de Dados
   escreval("O valor da area desse trapezio e: ",area:4:3)
   
fimalgoritmo